export  {valorCarta}  from './valor-carta'
export  {pedirCarta}  from './pedir-carta'
export  {crearDeck}  from './crear-deck'
export {turnoComputadora} from './turno-computadora'
export {crearCartaHTML} from './crear-carta-html'